// Code generated by tygo. DO NOT EDIT.

//////////
// source: day.go

export interface Day {
  id: number /* int */;
  date: string; // "2026-05-11"
  day_type: string; // "full" | "half" | "light" | "unset"
  wake_time: string; // "08:30" or ""
  notes: string;
  focus: string;
  tasks: Task[];
}

//////////
// source: task.go

export interface Task {
  id: number /* int */;
  label: string;
  completed: boolean;
  sort_order: number /* int */;
  source: string; // "template" | "custom"
}

//////////
// source: week.go

export interface Week {
  id: number /* int */;
  week_start: string; // "2026-05-11" — always a Monday
  days: Day[];
}
